title: Selina' World
theme: jekyll-theme-hpstr

plugins:
  - jekyll-seo-tag

collections:
  categories:
    output: true

defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
