destination: _site/
url: "http://127.0.0.1:4011"
baseurl: "/life-pdf"
port: 4011
output: pdf
product: life
print_title: life documentation
print_subtitle: version 1.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: life_sidebar
